trigger:
- main

variables:
  azureSubscription: 'eecd4c52-26ac-46e8-a025-2324a19b7a34'
  webAppName: 'java-spring-boot7'
  environmentName: 'java-spring-boot7'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'MyWebApp/pom.xml'

    - powershell: |
        $timestamp = Get-Date -Format "yyyyMMddHHmmss"
        Write-Host "##vso[task.setvariable variable=ArtifactVersion]$timestamp"
      displayName: 'Set Artifact Version'

    - script: |
        mkdir "$(Build.ArtifactStagingDirectory)/$(ArtifactVersion)"
        cp -r $(System.DefaultWorkingDirectory)/**/target/*.?(war|jar) "$(Build.ArtifactStagingDirectory)/$(ArtifactVersion)/"
      displayName: 'Copy Files to Artifact Directory'

    - publish: $(Build.ArtifactStagingDirectory)/$(ArtifactVersion)
      artifact: drop
      displayName: 'Publish Artifact'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployLinuxWebApp
    displayName: Deploy Linux Web App
    environment: $(environmentName)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: java-spring-boot7'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/$(ArtifactVersion)/**/*.?(war|jar)'
